#!/bin/bash

# ppom help 명령어 - 도움말 + 실제 명세 응답 포함

echo "# ppomppu-crawler 도움말"
echo ""
echo "> \`/ppom help\` 처럼 편리하게 ppomppu-crawler 도구와 엔드포인트 정보 확인!"
echo ""
echo "---"
echo ""
echo "## 🚀 사용 가능한 명령어"
echo ""
echo "### 기본 사용법"
echo "\`\`\`bash"
echo "/ppom help                      # 이 도움말 표시"
echo "/ppom freeboard [page]          # 자유게시판 조회 (기본: 1페이지)"
echo "/ppom baseball [page]           # 야구 게시판 조회"
echo "/ppom ppomppu [page]            # 뽐뿌 일반 게시판 조회"
echo "/ppom stock [page]              # 주식 게시판 조회"
echo "/ppom analyze <board> [page]    # 게시판 분석 (키워드, 통계, 카테고리)"
echo "\`\`\`"
echo ""
echo "---"
echo ""
echo "## 📡 엔드포인트 응답 명세"
echo ""
echo "### 1️⃣ GET /tools - MCP 도구 목록"
echo ""
echo "\`\`\`json"
curl -s "http://localhost:3008/tools" | head -80
echo ""
echo "... (6개 도구 포함)"
echo "\`\`\`"
echo ""
echo "### 2️⃣ GET /freeboard?page=1 - 자유게시판 데이터"
echo ""
echo "\`\`\`json"
curl -s "http://localhost:3008/freeboard?page=1" | jq '.data | {boardId, page, postCount, posts: .posts[0:3]}' 2>/dev/null || curl -s "http://localhost:3008/freeboard?page=1" | head -60
echo ""
echo "... (30개 게시물 포함)"
echo "\`\`\`"
echo ""
echo "### 3️⃣ GET /analyze?board=freeboard&page=1 - 게시판 분석"
echo ""
echo "\`\`\`json"
curl -s "http://localhost:3008/analyze?board=freeboard&page=1" | jq '.analysis | {timeline, keywords: .keywords.keywords[0:5], categoriesCount: (.categories | length)}' 2>/dev/null || curl -s "http://localhost:3008/analyze?board=freeboard&page=1" | head -60
echo ""
echo "... (타임라인, 키워드, 카테고리, 참여도, 상위 게시물 포함)"
echo "\`\`\`"
echo ""
echo "---"
echo ""
echo "## 📊 응답 필드 설명"
echo ""
echo "| 필드 | 설명 |"
echo "|------|------|"
echo "| \`boardId\` | 게시판 ID (freeboard, baseball, ppomppu, stock) |"
echo "| \`page\` | 요청한 페이지 번호 |"
echo "| \`posts\` | 게시물 배열 (제목, 작성자, 조회수, 추천수 등) |"
echo "| \`timeline\` | 시간대별 게시물 분포 |"
echo "| \`keywords\` | 핵심 키워드 (상위 5개) |"
echo "| \`categories\` | 게시물 카테고리 분류 |"
echo "| \`participation\` | 평균 추천수, 최대 추천수 등 |"
echo ""
